import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillGithub,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import profile from "../public/profile.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ankit's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">meankitdas</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  href="#"
                  className=" bg-gradient-to-r from-teal-500 to-teal-600 text-white px-4 py-2 rounded-md ml-5"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h1 className="text-5xl py-2 text-teal-600 font-burtons">
              Hi, I'm Ankit Das
            </h1>
            <h3 className="text-2xl py-2">A Full-Stack Developer</h3>
            <p className=" text-md py-5 leading-8 text-gray-800">
              Always code as if the guy who ends up maintaning your code will be
              a violent psychopath who knows where you live.{" "}
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-10 py-3 text-gray-600">
            <a href="https://twitter.com/its_ankitdas/" target="_blank">
              <AiFillTwitterCircle />
            </a>
            <a href="https://github.com/meankitdas/" target="_blank">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/itsankitdas/" target="_blank">
              <AiFillLinkedin />
            </a>
            <a href="https://www.instagram.com/its.ankitdas/" target="_blank">
              <AiFillInstagram />
            </a>
          </div>
          <div className=" mx-auto mt-20 items-end relative w-80 h-80">
            <Image src={profile} sizes/>
          </div>
        </section>
        <section>
          
        </section>
      </main>
    </div>
  );
}
